version: '2'
volumes:
  bundle_cache:
    driver: local
services:
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
     - "3000:3000"
    volumes:
     - .:/app
     - bundle_cache:/usr/local/bundle
    tty: true
    environment:
      - SPRING_TMP_PATH=tmp
      - SPRING_SOCKET=tmp/spring.sock
      - SPRING_PIDFILE=tmp/spring.pid
    depends_on:
      - spring
  spring:
    build: .
    command: spring server
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - SPRING_TMP_PATH=tmp
      - SPRING_SOCKET=tmp/spring.sock
      - SPRING_PIDFILE=tmp/spring.pid
